package com.zdv.yuncang.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zdv.yuncang.ZDVOrderItem;
import com.zdv.yuncang.ZDVOrderDetailItem;

import com.zdv.yuncang.dao.ZDVOrderItemDao;
import com.zdv.yuncang.dao.ZDVOrderDetailItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zDVOrderItemDaoConfig;
    private final DaoConfig zDVOrderDetailItemDaoConfig;

    private final ZDVOrderItemDao zDVOrderItemDao;
    private final ZDVOrderDetailItemDao zDVOrderDetailItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zDVOrderItemDaoConfig = daoConfigMap.get(ZDVOrderItemDao.class).clone();
        zDVOrderItemDaoConfig.initIdentityScope(type);

        zDVOrderDetailItemDaoConfig = daoConfigMap.get(ZDVOrderDetailItemDao.class).clone();
        zDVOrderDetailItemDaoConfig.initIdentityScope(type);

        zDVOrderItemDao = new ZDVOrderItemDao(zDVOrderItemDaoConfig, this);
        zDVOrderDetailItemDao = new ZDVOrderDetailItemDao(zDVOrderDetailItemDaoConfig, this);

        registerDao(ZDVOrderItem.class, zDVOrderItemDao);
        registerDao(ZDVOrderDetailItem.class, zDVOrderDetailItemDao);
    }
    
    public void clear() {
        zDVOrderItemDaoConfig.getIdentityScope().clear();
        zDVOrderDetailItemDaoConfig.getIdentityScope().clear();
    }

    public ZDVOrderItemDao getZDVOrderItemDao() {
        return zDVOrderItemDao;
    }

    public ZDVOrderDetailItemDao getZDVOrderDetailItemDao() {
        return zDVOrderDetailItemDao;
    }

}
