package com.zdv.yuncang;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ZDVORDER_DETAIL_ITEM".
 */
public class ZDVOrderDetailItem {

    private Long id;
    private String ocode;
    private String pcode;
    private String barcode;
    private String name;
    private String unit;
    private String act_num;
    private String number;
    private String price;
    private String memprice;
    private String cost_type;
    private String address;
    private String item_code;
    private String remark;
    private String cwpsl;
    private String status;

    public ZDVOrderDetailItem() {
    }

    public ZDVOrderDetailItem(Long id) {
        this.id = id;
    }

    public ZDVOrderDetailItem(Long id, String ocode, String pcode, String barcode, String name, String unit, String act_num, String number, String price, String memprice, String cost_type, String address, String item_code, String remark, String cwpsl, String status) {
        this.id = id;
        this.ocode = ocode;
        this.pcode = pcode;
        this.barcode = barcode;
        this.name = name;
        this.unit = unit;
        this.act_num = act_num;
        this.number = number;
        this.price = price;
        this.memprice = memprice;
        this.cost_type = cost_type;
        this.address = address;
        this.item_code = item_code;
        this.remark = remark;
        this.cwpsl = cwpsl;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOcode() {
        return ocode;
    }

    public void setOcode(String ocode) {
        this.ocode = ocode;
    }

    public String getPcode() {
        return pcode;
    }

    public void setPcode(String pcode) {
        this.pcode = pcode;
    }

    public String getBarcode() {
        return barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getAct_num() {
        return act_num;
    }

    public void setAct_num(String act_num) {
        this.act_num = act_num;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getMemprice() {
        return memprice;
    }

    public void setMemprice(String memprice) {
        this.memprice = memprice;
    }

    public String getCost_type() {
        return cost_type;
    }

    public void setCost_type(String cost_type) {
        this.cost_type = cost_type;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getItem_code() {
        return item_code;
    }

    public void setItem_code(String item_code) {
        this.item_code = item_code;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getCwpsl() {
        return cwpsl;
    }

    public void setCwpsl(String cwpsl) {
        this.cwpsl = cwpsl;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
