package com.zdv.yuncang;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ZDVORDER_ITEM".
 */
public class ZDVOrderItem {

    private Long id;
    private String code;
    private String ucode;
    private String createtime;
    private String totalprice;
    private String payprice;
    private String paystate;
    private String status;
    private String coster;
    private String company_id;
    private String solve;
    private String shoptype;
    private String remark;

    public ZDVOrderItem() {
    }

    public ZDVOrderItem(Long id) {
        this.id = id;
    }

    public ZDVOrderItem(Long id, String code, String ucode, String createtime, String totalprice, String payprice, String paystate, String status, String coster, String company_id, String solve, String shoptype, String remark) {
        this.id = id;
        this.code = code;
        this.ucode = ucode;
        this.createtime = createtime;
        this.totalprice = totalprice;
        this.payprice = payprice;
        this.paystate = paystate;
        this.status = status;
        this.coster = coster;
        this.company_id = company_id;
        this.solve = solve;
        this.shoptype = shoptype;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getUcode() {
        return ucode;
    }

    public void setUcode(String ucode) {
        this.ucode = ucode;
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    public String getTotalprice() {
        return totalprice;
    }

    public void setTotalprice(String totalprice) {
        this.totalprice = totalprice;
    }

    public String getPayprice() {
        return payprice;
    }

    public void setPayprice(String payprice) {
        this.payprice = payprice;
    }

    public String getPaystate() {
        return paystate;
    }

    public void setPaystate(String paystate) {
        this.paystate = paystate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCoster() {
        return coster;
    }

    public void setCoster(String coster) {
        this.coster = coster;
    }

    public String getCompany_id() {
        return company_id;
    }

    public void setCompany_id(String company_id) {
        this.company_id = company_id;
    }

    public String getSolve() {
        return solve;
    }

    public void setSolve(String solve) {
        this.solve = solve;
    }

    public String getShoptype() {
        return shoptype;
    }

    public void setShoptype(String shoptype) {
        this.shoptype = shoptype;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
